### ISSUE TITLE
SNPPar Installation

### ISSUE THREAD

**Issue by githubzhw2018** [d-j-e/SNPPar#17]
I used the command "pip install git+https://github.com/d-j-e/SNPPar" to install SNPPar, it was stopped by a reason that Biopython requires Python 3.6 or later, Python 2.7 detected. When I used the command "pip3 install git+https://github.com/d-j-e/SNPPa" to install SNPPar, it was done successfully. But the snppar software did not work. My system is Ubuntu LTS 18.04, python version is  3.6.9, biopython version is 1.78. How can I  make it worked.

**Comment by The1stMartian** [comment]
Try executing using the command "python3 snppar.py" or equivalent to specify the use of python3. If you use "python snppar.py" you may be executing with python 2.7.

**Comment by githubzhw2018** [comment]
________________________________
发件人: The1stMartian <notifications@github.com>
发送时间: 2020年10月19日 19:33
收件人: d-j-e/SNPPar <SNPPar@noreply.github.com>
抄送: githubzhw2018 <zhwzju@outlook.com>; Author <author@noreply.github.com>
主题: Re: [d-j-e/SNPPar] SNPPar Installation (#17)


Try executing using the command "python3 snppar.py" or equivalent to specify the use of python3. If you use "python snppar.py" you may be executing with python 2.7.

―

**Comment by githubzhw2018** [comment]
Thank you for your help, but the software of snppar.py did not work. When I used the command as "python2 snppar.py ", and the software reports error "File "snppar.py", line 2558SyntaxError: Non-ASCII character '\xc3' in file snppar.py on line 2558, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details"
Could you share your experiences of using the software of snppar.py. Thanks again.


Hong-Wei Zhou
________________________________
发件人: Zhou Hong-Wei <zhwzju@outlook.com>
发送时间: 2020年10月21日 4:09
收件人: d-j-e/SNPPar <reply@reply.github.com>
主题: 回复: [d-j-e/SNPPar] SNPPar Installation (#17)


________________________________
发件人: The1stMartian <notifications@github.com>
发送时间: 2020年10月19日 19:33
收件人: d-j-e/SNPPar <SNPPar@noreply.github.com>
抄送: githubzhw2018 <zhwzju@outlook.com>; Author <author@noreply.github.com>
主题: Re: [d-j-e/SNPPar] SNPPar Installation (#17)


Try executing using the command "python3 snppar.py" or equivalent to specify the use of python3. If you use "python snppar.py" you may be executing with python 2.7.

―

**Comment by scwatts** [comment]
Hi Hong-Wei Zhou, I've merged a PR to fix this issue you've described. Please let us know if you have any other problems!
