### ISSUE TITLE
Error and fix

### ISSUE THREAD

**Issue by The1stMartian** [d-j-e/SNPPar#18]
I am doing an analysis from individual genes. My inputs are an "mFASTA" nucleotide alignment file, and a file with SNP locations. There is a bug at line 256:

File "snppar.py", line 256, in readMFASTA
    all_calls[i]+=line[i].upper()
IndexError: list index out of range

The original line of code is:
                        for i in range(len(line.rstrip())):

This should actually read: 
                         for i in range(len(all_calls)):

Explanation: The script is incorrectly iterating over all nucleotides in the sequence instead of all indices in the SNP location file that goes along with the mFASTA file.

**Comment by scwatts** [comment]
Hi The1stMartian, thanks for opening this issue. I believe the mFASTA file should only contain SNPs listed in the SNP position file. I suspect the mFASTA you're using contains more SNPs/nucleotides than are listed in the SNP position file, causing the error you've described.

I'll close this issue for now but if you continue to encounter this error, could you please reopen and post the input files you've used.
