### ISSUE TITLE
SNPPar install issue

### ISSUE THREAD

**Issue by sbberes** [d-j-e/SNPPar#20]
David,
  First thank you for your software development. I have run into install error messages indicating that there is an incompatibility associated with Biopython-1.78 and snppar.py involving Bio.Alphabet indicating that Bio.Alphabet is no longer part of Biopython. I do however find that "/Users/sbberes/opt/anaconda3/lib/python3.8/site-packages/Bio/Alphabet/__init__.py" is present. Below is the output that I get when trying to install and run snppar, sbberes@houstonmethodist.org - thanks for any assistance (p.s. a conda install would be nice):

(base) ➜  Desktop pip install git+https://github.com/d-j-e/SNPPar
Collecting git+https://github.com/d-j-e/SNPPar
  Cloning https://github.com/d-j-e/SNPPar to /private/var/folders/4j/l7l40pq12tz8drwfw52y59n40000gn/T/pip-req-build-zix51bmy
Collecting biopython>=1.66
  Downloading biopython-1.78-cp38-cp38-macosx_10_9_x86_64.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 3.8 MB/s
Collecting ete3
  Downloading ete3-3.1.2.tar.gz (4.7 MB)
     |████████████████████████████████| 4.7 MB 3.9 MB/s
Collecting phylo-treetime
  Downloading phylo_treetime-0.8.0-py3-none-any.whl (125 kB)
     |████████████████████████████████| 125 kB 10.2 MB/s
Requirement already satisfied: numpy in /Users/sbberes/opt/anaconda3/lib/python3.8/site-packages (from biopython>=1.66->snppar==1.0) (1.19.2)
Requirement already satisfied: pandas>=0.17.1 in /Users/sbberes/opt/anaconda3/lib/python3.8/site-packages (from phylo-treetime->snppar==1.0) (1.1.3)
Requirement already satisfied: scipy>=0.16.1 in /Users/sbberes/opt/anaconda3/lib/python3.8/site-packages (from phylo-treetime->snppar==1.0) (1.5.2)
Requirement already satisfied: matplotlib>=2.0; python_version >= "3.6" in /Users/sbberes/opt/anaconda3/lib/python3.8/site-packages (from phylo-treetime->snppar==1.0) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7.3 in /Users/sbberes/opt/anaconda3/lib/python3.8/site-packages (from pandas>=0.17.1->phylo-treetime->snppar==1.0) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /Users/sbberes/opt/anaconda3/lib/python3.8/site-packages (from pandas>=0.17.1->phylo-treetime->snppar==1.0) (2020.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /Users/sbberes/opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=2.0; python_version >= "3.6"->phylo-treetime->snppar==1.0) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/sbberes/opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=2.0; python_version >= "3.6"->phylo-treetime->snppar==1.0) (1.3.0)
Requirement already satisfied: certifi>=2020.06.20 in /Users/sbberes/opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=2.0; python_version >= "3.6"->phylo-treetime->snppar==1.0) (2020.6.20)
Requirement already satisfied: pillow>=6.2.0 in /Users/sbberes/opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=2.0; python_version >= "3.6"->phylo-treetime->snppar==1.0) (8.0.1)
Requirement already satisfied: cycler>=0.10 in /Users/sbberes/opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=2.0; python_version >= "3.6"->phylo-treetime->snppar==1.0) (0.10.0)
Requirement already satisfied: six>=1.5 in /Users/sbberes/opt/anaconda3/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas>=0.17.1->phylo-treetime->snppar==1.0) (1.15.0)
Building wheels for collected packages: snppar, ete3
  Building wheel for snppar (setup.py) ... done
  Created wheel for snppar: filename=snppar-1.0-py3-none-any.whl size=47747 sha256=f8685d951ab017365c66d310892b71de7d163658fc0f6f89e6ca86a81270e973
  Stored in directory: /private/var/folders/4j/l7l40pq12tz8drwfw52y59n40000gn/T/pip-ephem-wheel-cache-f3zpirmt/wheels/ca/85/92/7592af7eefda06c8a1d37239b3ad1304b4391810c7979e00ba
  Building wheel for ete3 (setup.py) ... done
  Created wheel for ete3: filename=ete3-3.1.2-py3-none-any.whl size=2272998 sha256=544565f8bb5e9b74fb80bce2cff88843d48622bfbd2bf115ea9737d0ea391a9e
  Stored in directory: /Users/sbberes/Library/Caches/pip/wheels/78/96/a0/973292c4813e6b39b611bec535521655088425516959768f46
Successfully built snppar ete3
Installing collected packages: biopython, ete3, phylo-treetime, snppar
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

phylo-treetime 0.8.0 requires biopython<=1.76,>=1.66, but you'll have biopython 1.78 which is incompatible.
Successfully installed biopython-1.78 ete3-3.1.2 phylo-treetime-0.8.0 snppar-1.0
(base) ➜  Desktop which snppar
/Users/sbberes/opt/anaconda3/bin/snppar
(base) ➜  Desktop snppar
Traceback (most recent call last):
  File "/Users/sbberes/opt/anaconda3/bin/snppar", line 5, in <module>
    from snppar import main
  File "/Users/sbberes/opt/anaconda3/bin/snppar.py", line 38, in <module>
    from Bio.Alphabet import IUPAC, generic_dna
  File "/Users/sbberes/opt/anaconda3/lib/python3.8/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
(base) ➜  Desktop snppar -h
Traceback (most recent call last):
  File "/Users/sbberes/opt/anaconda3/bin/snppar", line 5, in <module>
    from snppar import main
  File "/Users/sbberes/opt/anaconda3/bin/snppar.py", line 38, in <module>
    from Bio.Alphabet import IUPAC, generic_dna
  File "/Users/sbberes/opt/anaconda3/lib/python3.8/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

**Comment by scwatts** [comment]
Hi @sbberes, thanks for opening the issue. The first error is related to phylo-treetime requiring biopython to be between version 1.66 and 1.76, and the second error is caused by the use of Bio.Alphabet.generic_dna in biopython version 1.78.

I've adjusted the SNPPar dependencies in `setup.py` accordingly and so if you try reinstalling again, you should no longer encounter these errors.

**Comment by sbberes** [comment]
Stephen Watts,
                That was incredibly fast – thanks so much. It all seems to be working with the fresh install.
Regards,
SBB


Stephen B. Beres Ph.D.
Professor of Pathology and Genomic Medicine
Institute for Academic Medicine
Director of Microbial Informatics
Center for Molecular and Translational Infectious Disease Research
Houston Methodist Research Institute
6670 Bertner Ave.
Houston, TX 77030
MS RIB R6-111
(713) 441-5067
sbberes@houstonmethodist.org (Beres, Stephen B.)
